@startuml

/' diagram meta data start
config=CallConfiguration;
{
  "rootMethod": "com.richdear.privacykeyboard.inputmethod.latin.e2ee.E2EEMenuView#clearFocusEditTextView()",
  "projectClassification": {
    "searchMode": "OpenProject", // OpenProject, AllProjects
    "includedProjects": "",
    "pathEndKeywords": "*.impl",
    "isClientPath": "",
    "isClientName": "",
    "isTestPath": "",
    "isTestName": "",
    "isMappingPath": "",
    "isMappingName": "",
    "isDataAccessPath": "",
    "isDataAccessName": "",
    "isDataStructurePath": "",
    "isDataStructureName": "",
    "isInterfaceStructuresPath": "",
    "isInterfaceStructuresName": "",
    "isEntryPointPath": "",
    "isEntryPointName": "",
    "treatFinalFieldsAsMandatory": false
  },
  "graphRestriction": {
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "removeByInheritance": "", // inheritance/annotation based filtering is done in a second step
    "removeByAnnotation": "",
    "removeByClassPackage": "", // cleanup the graph after inheritance/annotation based filtering is done
    "removeByClassName": "",
    "cutMappings": false,
    "cutEnum": true,
    "cutTests": true,
    "cutClient": true,
    "cutDataAccess": true,
    "cutInterfaceStructures": true,
    "cutDataStructures": true,
    "cutGetterAndSetter": true,
    "cutConstructors": true
  },
  "graphTraversal": {
    "forwardDepth": 3,
    "backwardDepth": 3,
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "hideMappings": false,
    "hideDataStructures": false,
    "hidePrivateMethods": true,
    "hideInterfaceCalls": true, // indirection: implementation -> interface (is hidden) -> implementation
    "onlyShowApplicationEntryPoints": false, // root node is included
    "useMethodCallsForStructureDiagram": "ForwardOnly" // ForwardOnly, BothDirections, No
  },
  "details": {
    "aggregation": "GroupByClass", // ByClass, GroupByClass, None
    "showMethodParametersTypes": false,
    "showMethodParametersNames": false,
    "showMethodReturnType": false,
    "showPackageLevels": 2,
    "showCallOrder": false,
    "edgeMode": "MethodsOnly", // TypesOnly, MethodsOnly, TypesAndMethods, MethodsAndDirectTypeUsage
    "showDetailedClassStructure": false
  },
  "rootClass": "com.richdear.privacykeyboard.inputmethod.latin.e2ee.E2EEMenuView",
  "extensionCallbackMethod": "" // qualified.class.name#methodName - signature: public static String method(String)
}
diagram meta data end '/



digraph g {
    rankdir="LR"
    splines=polyline
    

'nodes 
subgraph cluster_1551067314 { 
   	label=richdear
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   subgraph cluster_1287280433 { 
   	label=privacykeyboard
	labeljust=l
	fillcolor="#d8d8d8"
	style=filled
   
   subgraph cluster_115521613 { 
   	label=E2EEMenuView
	labeljust=l
	fillcolor=white
	style=filled
   
   E2EEMenuView1648205996XXXclearFocusEditTextView0[
	label="+ clearFocusEditTextView()"
	style=filled
	fillcolor=white
	tooltip="E2EEMenuView

null"
	penwidth=4
	fontcolor=darkgreen
];
} 

subgraph cluster_2133923228 { 
   	label=LatinIME
	labeljust=l
	fillcolor=white
	style=filled
   
   LatinIME1270398895XXXonShowInputRequested1328349477[
	label="+ onShowInputRequested()"
	style=filled
	fillcolor=white
	tooltip="LatinIME

null"
	fontcolor=darkgreen
];
} 
} 
} 

'edges    
LatinIME1270398895XXXonShowInputRequested1328349477 -> E2EEMenuView1648205996XXXclearFocusEditTextView0;
    
}
@enduml