@startuml
'https://plantuml.com/class-diagram

KeyUtil -- SignedPreKeyStoreFullImlementation: Uses >
KeyUtil -- PreKeyStoreFullImlementation: Uses >


class SignedPreKeyStoreFullImlementation{
    store: Map<Integer, Byte>
    loadSignedPreKeys(): List<SignedPrekeyRecord>
    storeSignedPreKey(signedPreKeyId, record)
}

class PreKeyStoreFullImlementation{
    store: Map<Integer, PreKeyWithStatus>
    loadPreKey(): PreKeyRecord
    storePreKey(preKeyId, record)
}

class KeyUtil{
    generateAndStoreOneTimePreKey(protocolStore, preKeyId): PreKeyRecord
    generateAndStoreSignedPreKey(protocolStore, metadataStore): SignedPrekeyRecord
    generateIdentityKeyPair():IdentityKeyPair
}

@enduml